main: su.nightexpress.coinsengine.CoinsEnginePlugin
version: '${project.version}'
api-version: 1.20
name: CoinsEngine
author: NightExpress
desciption: Unlimited virtual currencies and server economy.
depend: [ nightcore ]
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - DeluxeCoinflip
load: STARTUP
